[paths]
log_file = "backup.log"
# Location of the borg repository
borg_repo = ""
# The path that will be backed up
backup_location = ""
# A directory in which the config.zip can be cached
cache_location = ""

[borg]
# if the borg repo is encrypted: set to true. The passphrase will have to be put into the .env file 
encrypted = true
# if the borg repo is accessed remotly: set to true. The command will have to be put into the .env file 
rsh = true

[urls]
healthcheck = "<url>"
